### PR TITLE
Refactor/mark/GitHub action workflows cherry pick

### PR DESCRIPTION
**Pull request by arminsabouri**
Wait for #373 to go in first

### CODE REVIEW

**Comment by birozuru** [comment]
# eBurger report

**Comment by birozuru** [comment]
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (2 results) (High)
 - [events-access](#events-access) (1 results) (Low)
 - [events-maths](#events-maths) (2 results) (Low)
 - [missing-zero-check](#missing-zero-check) (2 results) (Low)
 - [calls-loop](#calls-loop) (1 results) (Low)
 - [timestamp](#timestamp) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (3 results) (Informational)
 - [too-many-digits](#too-many-digits) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42) sends eth to arbitrary user
	Dangerous calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L45-L84


## events-access
Impact: Low
Confidence: Medium
 - [ ] ID-2
[Faucet.setOwner(address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L53-L55) should emit an event for: 
	- [owner = account](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L54) 

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L53-L55


## events-maths
Impact: Low
Confidence: Medium
 - [ ] ID-3
[Faucet.setLockTime(uint256)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L61-L63) should emit an event for: 
	- [lockTime = amount * 60](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L62) 

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L61-L63


 - [ ] ID-4
[Faucet.setWithdrawAmount(uint256)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L57-L59) should emit an event for: 
	- [withdrawAmount = amount](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L58) 

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L57-L59


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-5
[Faucet.setOwner(address).account](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L53) lacks a zero-check on :
		- [owner = account](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L54)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L53


 - [ ] ID-6
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L50


## calls-loop
Impact: Low
Confidence: Medium
 - [ ] ID-7
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42) has external calls inside a loop: [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L40)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42


## timestamp
Impact: Low
Confidence: Medium
 - [ ] ID-8
[Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42) uses timestamp for comparisons
	Dangerous comparisons:
	- [require(bool,string)(block.timestamp >= nextRequestAt[account],Insufficient time between requests)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L36)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-9
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L2)
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-10
Reentrancy in [Faucet.requestFundsByAddress(address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42):
	External calls:
	- [address(account).transfer(withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L40)
	Event emitted after the call(s):
	- [Transfer(account,withdrawAmount)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L41)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L33-L42


 - [ ] ID-11
Reentrancy in [Faucet.withdrawFunds()](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L44-L47):
	External calls:
	- [address(owner).transfer(address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L45)
	Event emitted after the call(s):
	- [Withdraw(owner,address(this).balance)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L46)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L44-L47


 - [ ] ID-12
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L45-L84):
	External calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L81)
	Event emitted after the call(s):
	- [Mint(destination,amount,bitcoinBlockHeight,metadata)](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L83)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Minting.sol#L45-L84


## too-many-digits
Impact: Informational
Confidence: Medium
 - [ ] ID-13
[Faucet.slitherConstructorVariables()](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L4-L69) uses literals with too many digits:
	- [withdrawAmount = 1000000000000000](https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L7)

https://github.com/botanix-labs/Macbeth/blob/3f0a329df68c58491234a04a9967b5cbe3c527ed/contracts/src/Faucet.sol#L4-L69

**Comment by arminsabouri** [comment]
@birozuru todo which alert should be ticketed out and fixed

**Comment by arminsabouri** [comment]
@birozuru unfortuently there are some conflicts now :(

**Review by arminsabouri — COMMENTED** [review]
LGTM!

**Pull request merged**
