### PR TITLE
Change mainchain block commitment tracking to add conf window

### PR DESCRIPTION
**Pull request by stevenroose**
It's hard-coded set to 100. I'm unsure whether we should hard-code this like this (value to be picked) or set as a consensus variable somehow, or a config flag. I welcome suggestions.

### CODE REVIEW

**Comment by stevenroose** [comment]
I'm working on the integration test doing the right thing.

**Review by BatiGencho — DISMISSED** [review]

**Comment by arminsabouri** [comment]
blocked: eth unit tests are panicking.

**Review by scottmillner — DISMISSED** [review]

**Comment by stevenroose** [comment]
I rebased and now that inturn test passes locally. Let's await CI

**Review by BatiGencho — APPROVED** [review]

**Comment by arminsabouri** [comment]
TAck 2ca643a1924d586f643e48ba46eeaf8c535d8e39

**Pull request merged**
