### PR TITLE
add getBtcFees endpoint

### PR DESCRIPTION
**Pull request by scottmillner**

### CODE REVIEW

**Review by arminsabouri — APPROVED** [review]
🙌 🙌 🙌

**Comment by stevenroose** [comment]
What does this method actually return? A static fee value? Or a feerate? How is the feerate expressed, if so? The documentation reads "Returns the Bitcoin fees for a pegout transaction" which doesn't really mean anything.

**Comment by arminsabouri** [comment]
Yes its a static value until we move the fee to the botanix block headers. 
>The documentation reads "Returns the Bitcoin fees for a pegout transaction" which doesn't really mean anything.

Agreed. Documentation should specify fee rate

**Comment by stevenroose** [comment]
I'll add it. In other places could be done too.

**Comment by stevenroose** [comment]
https://github.com/botanix-labs/Macbeth/pull/15

**Pull request merged**
