### PR TITLE
authority: Improve readibility of highly indented function

### PR DESCRIPTION
**Pull request by stevenroose**
Suggested this in https://github.com/botanix-labs/Macbeth/pull/31 but didn't make it in.

### CODE REVIEW

**Comment by stevenroose** [comment]
I got some error trying to run cargo check with this

```

  CFLAGS = None
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wuninitialized" "-DMDBX_BUILD_FLAGS=\"-O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall -Wextra -Wno-unused-parameter -Wuninitialized\"" "-DMDBX_TXN_CHECKOWNER=0" "-DMDBX_DEBUG=1" "-DMDBX_ENABLE_PROFGC=1" "-o" "/var/cargo-target/debug/build/reth-mdbx-sys-917ecf0cb2358508/out/ccd9b65ad176fa1b-mdbx.o" "-c" "/home/steven/projects/botanix/Macbeth/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c"
  cargo:warning=gcc: error: unrecognized command-line option ‘-Wuninitialized"’; did you mean ‘-Wuninitialized’?

  exit status: 1

  --- stderr
  Failed to run rustfmt: No such file or directory (os error 2) (non-fatal, continuing)


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wuninitialized" "-DMDBX_BUILD_FLAGS=\"-O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall -Wextra -Wno-unused-parameter -Wuninitialized\"" "-DMDBX_TXN_CHECKOWNER=0" "-DMDBX_DEBUG=1" "-DMDBX_ENABLE_PROFGC=1" "-o" "/var/cargo-target/debug/build/reth-mdbx-sys-917ecf0cb2358508/out/ccd9b65ad176fa1b-mdbx.o" "-c" "/home/steven/projects/botanix/Macbeth/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c" with args "cc" did not execute successfully (status code exit status: 1).
```

I can't understand why rustfmt is required to build a dependency, though. But yeah I don't have rustfmt.

**Comment by arminsabouri** [comment]
This is a really good start! Today @scottmillner and I we're talking about refactoring the authority task into more of a task manager. The idea is to have the different listeners (block import, block miner, sync manager) on separate tokio tasks in the same runtime

@stevenroose any thoughts?

**Review by scottmillner — APPROVED** [review]
💪

**Comment by stevenroose** [comment]
> This is a really good start! Today @scottmillner and I we're talking about refactoring the authority task into more of a task manager. The idea is to have the different listeners (block import, block miner, sync manager) on separate tokio tasks in the same runtime
> 
> @stevenroose any thoughts?

Makes sense. Everything is on the same runtime anyway, right? In that case, you'd create more like green threads kinda, like async routines. That makes sense. Can make it more understandable than a single thread and I believe tokio should be low overhead?

**Pull request merged**
