### PR TITLE
Deployment Pipeline refix

### PR DESCRIPTION
**Pull request by birozuru**
- Cleaned out unneeded workflow files.
- Changed runners values to self-hosted runners
- Added test-suites to integration workflow

### CODE REVIEW

**Review by arminsabouri — APPROVED** [review]
Approach ACK. Maybe @ozymandias-rex  can also take a look.

**Review by ozymandias-rex — APPROVED** [review]
LGTM

**Review by BatiGencho — APPROVED** [review]

**Comment by BatiGencho** [comment]
@birozuru please fix the conflicts

**Comment by arminsabouri** [comment]
Can we close this?

**Comment by birozuru** [comment]
> Can we close this?

yes we can

**Pull request closed without merging**
