### PR TITLE
feat: removed all optimism-related stuff

### PR DESCRIPTION
**Pull request by rwlockbg**

### CODE REVIEW

**Comment by birozuru** [comment]
# eBurger report

**Comment by birozuru** [comment]
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (1 results) (High)
 - [missing-zero-check](#missing-zero-check) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L45-L84


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L50


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-2
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-3
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L45-L84):
	External calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L81)
	Event emitted after the call(s):
	- [Mint(destination,amount,bitcoinBlockHeight,metadata)](https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L83)

https://github.com/botanix-labs/Macbeth/blob/8108f4aaac0beecf487e9775af01c5e793773fe6/contracts/src/Minting.sol#L45-L84

**Comment by birozuru** [comment]
# eBurger report

**Comment by birozuru** [comment]
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (1 results) (High)
 - [missing-zero-check](#missing-zero-check) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L45-L84


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L50


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-2
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-3
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L45-L84):
	External calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L81)
	Event emitted after the call(s):
	- [Mint(destination,amount,bitcoinBlockHeight,metadata)](https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L83)

https://github.com/botanix-labs/Macbeth/blob/13e8a09160874641717eec3c6fda852eb02fa543/contracts/src/Minting.sol#L45-L84

**Comment by birozuru** [comment]
# eBurger report

**Comment by birozuru** [comment]
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (1 results) (High)
 - [missing-zero-check](#missing-zero-check) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L45-L84


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L50


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-2
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-3
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L45-L84):
	External calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L81)
	Event emitted after the call(s):
	- [Mint(destination,amount,bitcoinBlockHeight,metadata)](https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L83)

https://github.com/botanix-labs/Macbeth/blob/aaa60a158d2dfcb4c8b5194e4def1a5e2533bd40/contracts/src/Minting.sol#L45-L84

**Comment by birozuru** [comment]
# eBurger report

**Comment by birozuru** [comment]
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (1 results) (High)
 - [missing-zero-check](#missing-zero-check) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L45-L84


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L50


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-2
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-3
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L45-L84):
	External calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L81)
	Event emitted after the call(s):
	- [Mint(destination,amount,bitcoinBlockHeight,metadata)](https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L83)

https://github.com/botanix-labs/Macbeth/blob/efa2083a932376cd4f9fbe70e807555ed614d2f4/contracts/src/Minting.sol#L45-L84

**Comment by birozuru** [comment]
# eBurger report

**Comment by birozuru** [comment]
# Slither report
**THIS CHECKLIST IS NOT COMPLETE**. Use `--show-ignored-findings` to show all the results.
Summary
 - [arbitrary-send-eth](#arbitrary-send-eth) (1 results) (High)
 - [missing-zero-check](#missing-zero-check) (1 results) (Low)
 - [solc-version](#solc-version) (1 results) (Informational)
 - [reentrancy-unlimited-gas](#reentrancy-unlimited-gas) (1 results) (Informational)
## arbitrary-send-eth
Impact: High
Confidence: Medium
 - [ ] ID-0
[Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L45-L84) sends eth to arbitrary user
	Dangerous calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L45-L84


## missing-zero-check
Impact: Low
Confidence: Medium
 - [ ] ID-1
[Minting.mint(address,uint256,uint32,bytes,address).refundAddress](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L50) lacks a zero-check on :
		- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L81)

https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L50


## solc-version
Impact: Informational
Confidence: High
 - [ ] ID-2
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
	- VerbatimInvalidDeduplication
	- FullInlinerNonExpressionSplitArgumentEvaluationOrder
	- MissingSideEffectsOnSelectorAccess
	- StorageWriteRemovalBeforeConditionalTermination
	- AbiReencodingHeadOverflowWithStaticArrayCleanup
	- DirtyBytesArrayToStorage
	- InlineAssemblyMemorySideEffects
	- DataLocationChangeInInternalOverride
	- NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
	- [^0.8.13](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L2)

https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L2


## reentrancy-unlimited-gas
Impact: Informational
Confidence: Medium
 - [ ] ID-3
Reentrancy in [Minting.mint(address,uint256,uint32,bytes,address)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L45-L84):
	External calls:
	- [address(destination).transfer(amount)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L80)
	- [address(refundAddress).transfer(txCost)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L81)
	Event emitted after the call(s):
	- [Mint(destination,amount,bitcoinBlockHeight,metadata)](https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L83)

https://github.com/botanix-labs/Macbeth/blob/4817a7ac7311cbf2e928b4489593966ea73ff205/contracts/src/Minting.sol#L45-L84

**Review by arminsabouri — APPROVED** [review]

**Pull request merged**
